### ISSUE TITLE
[offer] git 기초 명령어에서 Vim 에디터 내용 추가 제안

### ISSUE THREAD

**Issue by Kimgeek** [Web-Skills-06/web-skills#16]
git에서 에디터로 vim을 사용하는데 vim 명령어도 입문자가 바로 쓰기엔 어렵다고 느꼈습니다. 그래서 Vim에 대한 설명과 강의 링크를 추가하려고 합니다.

**Comment by Ohjiwoo-lab** [comment]
vim을 추가하는 것도 좋을것 같네요! 추가해주세요 :)

**Comment by the-groot** [comment]
좋은 아이디어인거 같습니다
