### ISSUE TITLE
[docs] convention 문서화

### ISSUE THREAD

**Issue by Ohjiwoo-lab** [Web-Skills-06/web-skills#9]
목적 : 
commit message convention과 branch 이름 convention, branch 전략에 대한 내용을 .md 파일로 정리한다.

**Comment by Ohjiwoo-lab** [comment]
현재 commit message convention과 issue naming convention에 대한 1차적인 내용을 정리하여 올렸습니다. 계속 보면서 변경사항 반영하도록 하겠습니다. 각 convention에 해당하는 예시 등도 첨부할 예정입니다! 내일 또는 월요일 중으로 문서화 작업 마무리 하겠습니다!

**Comment by Ohjiwoo-lab** [comment]
일단 제가 정해놓은 issue convention에 따라 이름을 변경해보았습니다. 혹시 변경하고 싶은 부분 있으시면 언제든 반영하겠습니다!

**Comment by the-groot** [comment]
issue네임도 수정이 가능하군요

**Comment by Ohjiwoo-lab** [comment]
넵! 제목에서 오른쪽 끝으로 가면 Edit 버튼 있는데 그걸 누르면 수정가능합니다!
